CREATE TABLE IF NOT EXISTS teste (
	nome VARCHAR(10) NOT NULL,
    sobrenome VARCHAR (10) NOT NULL
)DEFAULT CHARSET = utf8;

DESC teste;

INSERT INTO teste VALUES
('Fulano', 'De Tal');

SELECT * FROM teste;

ALTER TABLE teste
ADD COLUMN id INT NOT NULL PRIMARY KEY FIRST;

DROP TABLE IF EXISTS alunos;

DROP TABLE IF EXISTS teste;